name: Download Kaggle Dataset

on:
  workflow_dispatch:  # This lets you trigger the workflow manually

jobs:
  download-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Set up Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download dataset
        run: kaggle datasets download -d fajobgiua/heart-attack-risk-assessment-dataset --unzip
