name: Sync Kaggle Notebooks

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Kaggle CLI
        run: |
          pip install kaggle
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Upload Folder to Kaggle
        run: |
          kaggle kernels push -p test/  # Replace with the correct folder path
